(function(){
'use strict';
var registros=[], orden={campo:'nombre_producto',direccion:1}, visibles={};
var solicitudProductosActiva=null;
var temporizadorOcultarProcesoProductos=null;
var columnas=[
{campo:'cod_barra',titulo:'COD.',ancho:'7%'},{campo:'nombre_producto',titulo:'PRODUCTO',ancho:'20%'},{campo:'NombreMarca',titulo:'MARCA',ancho:'10%'},{campo:'NombreCategoria',titulo:'CATEGORIA',ancho:'10%'},{campo:'stock_producto',titulo:'STOCK',ancho:'7%'},{campo:'precio_compra',titulo:'PRECIO LISTA',ancho:'9%'},{campo:'localnombre',titulo:'LOCAL',ancho:'10%'},{campo:'proveedor',titulo:'PROVEEDOR',ancho:'10%'},{campo:'promo',titulo:'PROMO',ancho:'7%'},{campo:'puntaje',titulo:'PUNTAJE',ancho:'6%'},{campo:'condicion_precio',titulo:'EDITAR PR.',ancho:'7%'}];
function e(v){return $('<div>').text(v==null?'':String(v)).html()}
function v(id){var x=document.getElementById(id);return x?x.value:''}
function sincronizarScrollTabla(){var cabecera=document.getElementById('productosCabeceraScroll'),cuerpo=document.getElementById('table_abm_producto');if(!cabecera||!cuerpo)return;cuerpo.addEventListener('scroll',function(){cabecera.scrollLeft=cuerpo.scrollLeft})}
var observadorLayoutProductos=null;
var observadorVisibilidadProductos=null;
function ajustarAltoListadoProductos(){
	var cuerpo=document.getElementById('table_abm_producto');
	var formulario=document.getElementById('divAbmProducto1');
	var pie=formulario?formulario.querySelector('.productos-footer'):null;
	if(!cuerpo||!formulario||!pie)return;
	var rectCuerpo=cuerpo.getBoundingClientRect();
	var rectPie=pie.getBoundingClientRect();
	if(rectCuerpo.width<=0||rectCuerpo.height<=0||rectPie.top<=rectCuerpo.top){
		cuerpo.style.removeProperty('height');
		cuerpo.style.removeProperty('max-height');
		return;
	}
	var altoDisponible=Math.max(0,Math.floor(rectPie.top-rectCuerpo.top-1));
	cuerpo.style.setProperty('height',altoDisponible+'px','important');
	cuerpo.style.setProperty('max-height',altoDisponible+'px','important');
}
function programarAjusteListadoProductos(){if(window.requestAnimationFrame)window.requestAnimationFrame(ajustarAltoListadoProductos);else window.setTimeout(ajustarAltoListadoProductos,0)}
function prepararLayoutListadoProductos(){
	sincronizarScrollTabla();
	programarAjusteListadoProductos();
	window.addEventListener('resize',programarAjusteListadoProductos);
	var formulario=document.getElementById('divAbmProducto1');
	var ventana=document.getElementById('divAbmProducto');
	var pie=formulario?formulario.querySelector('.productos-footer'):null;
	var proceso=document.getElementById('tbProcessProducto');
	var envoltorio=formulario?formulario.querySelector('.productos-tabla-wrap'):null;
	if(window.ResizeObserver){
		observadorLayoutProductos=new ResizeObserver(programarAjusteListadoProductos);
		if(formulario)observadorLayoutProductos.observe(formulario);
		if(envoltorio)observadorLayoutProductos.observe(envoltorio);
		if(pie)observadorLayoutProductos.observe(pie);
		if(proceso)observadorLayoutProductos.observe(proceso);
	}
	if(window.MutationObserver&&ventana){
		observadorVisibilidadProductos=new MutationObserver(programarAjusteListadoProductos);
		observadorVisibilidadProductos.observe(ventana,{attributes:true,attributeFilter:['class','style']});
	}
}
function datos(mas){obtener_datos_user();var d={useru:userid,passu:passuser,navegador:navegador,codigo:v('inptBuscarProducto1'),producto:v('inptBuscarProducto2'),marca:v('inptBuscarProducto3'),categoria:v('inptBuscarProducto4'),stock:v('inptBuscarProducto5'),proveedor:v('inptBuscarProducto6'),local:v('inptBuscarProducto7'),ConStock:v('inptBuscarProducto8'),promo:v('inptBuscarProducto9'),EditarPrecio:v('inptBuscarProducto10'),puntaje:v('inptBuscarProducto11'),estado:document.getElementById('inptSeleccEstadoBuscarProducto1').checked?'Activo':'Inactivo',formato:'json'};if(mas!==undefined)d.registrocargado=mas;return d}
function montar(){var c=document.getElementById('divAbmProducto1');if(!c||c.dataset.listadoProductos==='SI')return;c.dataset.listadoProductos='SI';c.className='catalogo-ventana divAbms productos-container';c.removeAttribute('style');c.innerHTML=[
'<div class="productos-header"><div><p class="pTituloB">Buscar <b>Productos</b></p></div><div class="productos-header-actions"><button class="producto-icon" onclick="verCerrarVentanaAbmProducto(\'1\',\'1\')"><img src="/GoodVentaElectroCasaMaric/iconos/add.png"></button><button class="producto-icon" onclick="abrirFiltrosProductoListado()"><img src="/GoodVentaElectroCasaMaric/iconos/etiquetafiltrar.png"></button><button class="producto-icon" onclick="minimizarabmproductos()"><img src="/GoodVentaElectroCasaMaric/iconos/minimizar2.png"></button><button class="producto-icon" onclick="verCerrarAbmProducto()"><img src="/GoodVentaElectroCasaMaric/iconos/botonCerrar.png"></button></div></div>',
'<div class="productos-toolbar"><div class="productos-search"><input id="inptBuscarProducto2" placeholder="Buscar por producto, codigo..." onkeyup="if(event.keyCode===13)buscarabmproducto()"><button class="producto-btn primario" onclick="buscarabmproducto()">Buscar</button></div><div class="productos-toolbar-actions"><button id="btnFiltrosProductoListado" class="producto-btn advertencia" onclick="abrirFiltrosProductoListado()">Filtros</button><button class="producto-btn columnas selector-columnas-trigger" aria-controls="panelColumnasProductos" aria-expanded="false" onclick="abrirColumnasProductoListado()">Columnas</button><button class="producto-btn claro" onclick="limpiarFiltrosProductoListado()">Limpiar</button></div></div>',
'<div id="productoFiltrosActivos" class="productos-chips"><span class="producto-chip vacio">Sin filtros aplicados</span></div>',
'<div class="productos-layout"><div class="productos-lista"><div class="productos-tabla-wrap"><div id="productosCabeceraScroll" class="productos-tabla-cabecera-scroll"><table class="tableCabeceraRegistro productos-tabla"><tr id="cabeceraListadoProductos"></tr></table></div><div id="table_abm_producto" class="productos-table-body"></div></div></div><aside class="productos-precios"><h3>OTROS PRECIOS</h3><div id="table_abm_producto_detalles_precios"></div></aside></div>',
'<div id="tbProcessProducto" class="productos-proceso productos-proceso-reposo" aria-live="polite" aria-hidden="true"><div class="productos-proceso-info"><span id="textoProgressProducto">Preparando búsqueda</span><strong id="porcentajeProgressProducto">0%</strong></div><div class="productos-progreso" role="progressbar" aria-label="Avance de carga de productos" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="divProgressProducto"></div></div><button type="button" id="btnCancelarCargaProducto" class="producto-btn productos-cancelar" onclick="cancelarCargaProducto()">Cancelar</button></div>',
'<div class="productos-footer"><div class="productos-footer-campo productos-footer-registros"><label for="inptRegistoCargadoProducto">Registros</label><input id="inptRegistoCargadoProducto" disabled></div><div class="productos-footer-campo productos-footer-seleccion"><label for="inptRegistroSeleccProducto">Registro seleccionado</label><input id="inptRegistroSeleccProducto" disabled></div><div class="productos-footer-actions"><button id="btnEditarProductos" class="producto-btn primario" onclick="verVentanaEditarProducto()">Editar</button><button id="btnAuditoriaProducto" class="producto-btn advertencia" onclick="verCerrarAuditoria(1)" style="display:none">Auditoria</button><button id="btnBajaDatosProductos" class="producto-btn peligro" onclick="verCerrarVentanaAbmdarDeBaja(1)">Dar de baja</button><button id="btnPuntosProductos" class="producto-btn exito" onclick="verCerrarFrmPuntos(\'1\',\'\')">Puntos</button><button id="btnGarantiaProducto" class="producto-btn primario" onclick="verCerrarGarantiasDesdeProducto(\'1\')">Garantia</button><button id="btnEnviarProductos" style="display:none"></button><button id="btnPreciosCategoriaProductos" style="display:none"></button><button id="btnEliminarProducto" style="display:none"></button><button id="btnVerConfigPrecios" style="display:none"></button></div></div>',
'<div id="panelColumnasProductos" class="productos-columnas-panel selector-columnas-panel"><header><b>Columnas visibles</b><button onclick="cerrarColumnasProductoListado()">&times;</button></header><div id="opcionesColumnasProductos"></div><footer><button class="producto-btn claro" onclick="restablecerColumnasProductoListado()">Restablecer</button></footer></div>',
'<div id="modalFiltrosProductoListado" class="productos-modal"><div class="productos-modal-overlay" onclick="cerrarFiltrosProductoListado()"></div><div class="productos-modal-box"><header><h3>Filtros de productos</h3><button onclick="cerrarFiltrosProductoListado()">&times;</button></header><div class="productos-modal-body">'+
'<div class="producto-estado"><b>Estado</b><label><input type="radio" name="estadoProductoListado" id="inptSeleccEstadoBuscarProducto1" checked> Activo</label><label><input type="radio" name="estadoProductoListado" id="inptSeleccEstadoBuscarProducto2"> Inactivo</label></div><label>Codigo<input id="inptBuscarProducto1"></label><label>Marca<select id="inptBuscarProducto3"></select></label><label>Categoria<select id="inptBuscarProducto4"></select></label><label>Stock menor o igual<input id="inptBuscarProducto5"></label><label>Proveedor<input id="inptBuscarProducto6"></label><label>Local<select id="inptBuscarProducto7"></select></label><label>Disponibilidad<select id="inptBuscarProducto8"><option value="">TODOS</option><option value="constock">CON STOCK</option><option value="sinstock">SIN STOCK</option></select></label><label>Promocion<select id="inptBuscarProducto9"><option value="">TODOS</option><option value="NO">NO</option><option value="SI">SI</option><option value="BLACK FRIDAY">BLACK FRIDAY</option><option value="REMATE">REMATE</option><option value="RECUPERADO">RECUPERADO</option></select></label><label>Precio editable<select id="inptBuscarProducto10"><option value="">TODOS</option><option value="SI">SI</option><option value="NO">NO</option></select></label><label>Puntaje<select id="inptBuscarProducto11"><option value="">TODOS</option><option value="1">SIN PUNTAJE</option><option value="2">CON PUNTAJE</option></select></label></div><footer><button class="producto-btn claro" onclick="limpiarFiltrosProductoListado(false)">Limpiar</button><button class="producto-btn primario" onclick="aplicarFiltrosProductoListado()">Aplicar</button></footer></div></div>'
].join('');cargarColumnas();cabecera();restaurarFiltros();prepararLayoutListadoProductos()}
function cargarColumnas(){try{visibles=JSON.parse(localStorage.getItem('columnasListadoProductos')||'{}')}catch(x){visibles={}}columnas.forEach(function(c){if(visibles[c.campo]===undefined)visibles[c.campo]=true});opcionesColumnas()}
function opcionesColumnas(){var c=document.getElementById('opcionesColumnasProductos');if(c)c.innerHTML=columnas.map(function(x){return '<label><input type="checkbox" '+(visibles[x.campo]?'checked':'')+' onchange="cambiarColumnaProductoListado(\''+x.campo+'\',this.checked)"> '+x.titulo+'</label>'}).join('')}
function cabecera(){var c=document.getElementById('cabeceraListadoProductos');if(c)c.innerHTML=columnas.filter(function(x){return visibles[x.campo]}).map(function(x){var i=orden.campo===x.campo?(orden.direccion===1?' &#9650;':' &#9660;'):'';return '<td class="td_registro producto-columna-orden" style="width:'+x.ancho+'" onclick="ordenarListadoProductos(\''+x.campo+'\')">'+x.titulo+'<span>'+i+'</span></td>'}).join('')}
function ocultos(r){var m={td_id:'cod_producto',td_datos_19:'cod_barra',td_datos_1:'nombre_producto',td_datos_12:'NombreImpuesto',td_datos_13:'NombreMarca',td_datos_11:'NombreCategoria',td_datos_2:'descripcion_producto',td_datos_3:'unidad_producto',td_datos_6:'stock_producto',td_datos_4:'precio_producto',td_datos_5:'precio_compra',td_datos_18:'totalcostos',td_datos_22:'proveedor',td_datos_24:'promo',td_datos_25:'puntaje',td_datos_108:'condicion_precio',td_datos_7:'cod_localFK',td_datos_8:'comision',td_datos_9:'estado',td_datos_10:'cod_localFK',td_datos_14:'cod_categoriaFK',td_datos_15:'cod_marcasFK',td_datos_16:'cod_ImpuestoFK',td_datos_17:'porcentaje',td_datos_20:'tipo',td_datos_23:'CodProveedor',td_datos_100:'insertadopor',td_datos_101:'editadopor',td_datos_102:'fecha_insert',td_datos_103:'fecha_edit',td_datos_104:'link',td_datos_105:'url',td_datos_106:'stockminimo',td_datos_107:'tipo_producto'};return Object.keys(m).map(function(id){return '<td id="'+id+'" style="display:none">'+e(r[m[id]])+'</td>'}).join('')}
function formato(c,v){if(['stock_producto','precio_compra'].indexOf(c)>=0){var n=Number(v);return isNaN(n)?e(v):n.toLocaleString('es-PY')}return e(v)}
function filas(){var c=document.getElementById('table_abm_producto');if(!c)return;var a=registros.slice().sort(function(x,y){return String(x[orden.campo]||'').localeCompare(String(y[orden.campo]||''),'es',{numeric:true})*orden.direccion});c.innerHTML=a.map(function(r){var t=columnas.filter(function(x){return visibles[x.campo]}).map(function(x){return '<td data-columna="'+x.campo+'" style="width:'+x.ancho+'">'+formato(x.campo,r[x.campo])+'</td>'}).join('');return '<table class="tableRegistroSearch producto-fila"><tr id="tbSelecRegistro" onclick="obtenerdatosabmProducto(this)">'+t+ocultos(r)+'</tr></table>'}).join('');programarAjusteListadoProductos()}
function estadoAriaColumnasProductos(abierto){var boton=document.querySelector('[aria-controls="panelColumnasProductos"]');if(boton)boton.setAttribute('aria-expanded',abierto?'true':'false')}
window.abrirColumnasProductoListado=function(){var panel=document.getElementById('panelColumnasProductos');if(!panel)return;var abierto=panel.classList.toggle('activo');estadoAriaColumnasProductos(abierto)};window.cerrarColumnasProductoListado=function(){var panel=document.getElementById('panelColumnasProductos');if(!panel)return;panel.classList.remove('activo');estadoAriaColumnasProductos(false)};window.cambiarColumnaProductoListado=function(c,s){visibles[c]=s;localStorage.setItem('columnasListadoProductos',JSON.stringify(visibles));cabecera();filas()};window.restablecerColumnasProductoListado=function(){columnas.forEach(function(c){visibles[c.campo]=true});localStorage.setItem('columnasListadoProductos',JSON.stringify(visibles));opcionesColumnas();cabecera();filas()};window.ordenarListadoProductos=function(c){if(orden.campo===c)orden.direccion*=-1;else orden={campo:c,direccion:1};cabecera();filas()};
window.abrirFiltrosProductoListado=function(){document.getElementById('modalFiltrosProductoListado').classList.add('activo')};window.cerrarFiltrosProductoListado=function(){document.getElementById('modalFiltrosProductoListado').classList.remove('activo')};
function resumen(){var c=document.getElementById('productoFiltrosActivos'),n=0,h=[];[['inptBuscarProducto1','Codigo'],['inptBuscarProducto3','Marca'],['inptBuscarProducto4','Categoria'],['inptBuscarProducto5','Stock'],['inptBuscarProducto6','Proveedor'],['inptBuscarProducto7','Local'],['inptBuscarProducto8','Disponibilidad'],['inptBuscarProducto9','Promo'],['inptBuscarProducto10','Precio'],['inptBuscarProducto11','Puntaje']].forEach(function(x){var z=document.getElementById(x[0]);if(z&&z.value!==''){var t=z.tagName==='SELECT'?z.options[z.selectedIndex].text:z.value;h.push('<span class="producto-chip">'+x[1]+': '+e(t)+'</span>');n++}});c.innerHTML=h.length?h.join(''):'<span class="producto-chip vacio">Sin filtros aplicados</span>';document.getElementById('btnFiltrosProductoListado').innerHTML=n?'Filtros ('+n+')':'Filtros'}
function guardarFiltros(){var d=datos();delete d.useru;delete d.passu;delete d.navegador;delete d.formato;localStorage.setItem('filtrosListadoProductos',JSON.stringify(d))}function restaurarFiltros(){try{var d=JSON.parse(localStorage.getItem('filtrosListadoProductos')||'{}'),m={codigo:'inptBuscarProducto1',producto:'inptBuscarProducto2',marca:'inptBuscarProducto3',categoria:'inptBuscarProducto4',stock:'inptBuscarProducto5',proveedor:'inptBuscarProducto6',local:'inptBuscarProducto7',ConStock:'inptBuscarProducto8',promo:'inptBuscarProducto9',EditarPrecio:'inptBuscarProducto10',puntaje:'inptBuscarProducto11'};Object.keys(m).forEach(function(k){var x=document.getElementById(m[k]);if(x&&d[k]!==undefined)x.value=d[k]});if(d.estado==='Inactivo'){document.getElementById('inptSeleccEstadoBuscarProducto1').checked=false;document.getElementById('inptSeleccEstadoBuscarProducto2').checked=true}}catch(x){}resumen()}
window.aplicarFiltrosProductoListado=function(){resumen();guardarFiltros();cerrarFiltrosProductoListado();buscarabmproducto()};window.limpiarFiltrosProductoListado=function(buscar){['inptBuscarProducto1','inptBuscarProducto2','inptBuscarProducto3','inptBuscarProducto4','inptBuscarProducto5','inptBuscarProducto6','inptBuscarProducto7','inptBuscarProducto8','inptBuscarProducto9','inptBuscarProducto10','inptBuscarProducto11'].forEach(function(id){var x=document.getElementById(id);if(x)x.value=''});document.getElementById('inptSeleccEstadoBuscarProducto1').checked=true;resumen();guardarFiltros();if(buscar!==false)buscarabmproducto()};
function actualizarProcesoProductos(porcentaje,texto,activo,estado){var proceso=document.getElementById('tbProcessProducto'),barra=document.getElementById('divProgressProducto'),valor=document.getElementById('porcentajeProgressProducto'),pista=barra?barra.parentNode:null,boton=document.getElementById('btnCancelarCargaProducto');porcentaje=Math.max(0,Math.min(100,Number(porcentaje)||0));if(temporizadorOcultarProcesoProductos){window.clearTimeout(temporizadorOcultarProcesoProductos);temporizadorOcultarProcesoProductos=null}if(proceso){proceso.setAttribute('aria-hidden',activo===true?'false':'true');proceso.classList.toggle('productos-proceso-activo',activo===true);proceso.classList.toggle('productos-proceso-cancelado',estado==='cancelado');proceso.classList.toggle('productos-proceso-error',estado==='error');proceso.classList.toggle('productos-proceso-reposo',activo!==true)}if(barra){barra.style.width=porcentaje+'%';barra.style.backgroundColor=''}if(valor)valor.textContent=porcentaje+'%';if(texto&&document.getElementById('textoProgressProducto'))document.getElementById('textoProgressProducto').textContent=texto;if(pista)pista.setAttribute('aria-valuenow',String(porcentaje));if(boton)boton.disabled=activo!==true||estado!=='activo';programarAjusteListadoProductos()}
function mostrarProcesoProductos(porcentaje,texto){actualizarProcesoProductos(porcentaje,texto,true,'activo')}
function finalizarProcesoProductos(porcentaje,texto,estado){var proceso=document.getElementById('tbProcessProducto');actualizarProcesoProductos(porcentaje,texto,true,estado||'completo');temporizadorOcultarProcesoProductos=window.setTimeout(function(){if(proceso){proceso.classList.remove('productos-proceso-activo','productos-proceso-cancelado','productos-proceso-error');proceso.classList.add('productos-proceso-reposo');proceso.setAttribute('aria-hidden','true')}temporizadorOcultarProcesoProductos=null;programarAjusteListadoProductos()},estado==='error'?1800:(estado==='cancelado'?450:800))}
function ajax(mas){var d=datos(mas);d.funt=mas===undefined?'buscar':'buscarmas';var peticion=$.ajax({data:d,url:'/GoodVentaElectroCasaMaric/php_system/abmproductos.php',type:'post',error:function(x,s){if(s==='abort')return;manejadordeerroresjquery(x.status,s,'abmventana');controldebusquedadProductos=false;finalizarProcesoProductos(Number(document.getElementById('porcentajeProgressProducto').textContent.replace('%',''))||0,'No se pudo completar la búsqueda','error')},success:function(r){try{var z=$.parseJSON(r);if(respuestaJqueryAjax(z['1'])===true){registros=mas===undefined?(Array.isArray(z[2])?z[2]:[]):registros.concat(Array.isArray(z[2])?z[2]:[]);filas();document.getElementById('inptRegistoCargadoProducto').value=z[3];registrocargadoproductos=Number(z[99]);if(mas===undefined)totalregistroproductos=Number(z[100]);var porcentaje=totalregistroproductos>0?Math.round((registrocargadoproductos*100)/totalregistroproductos):100;mostrarProcesoProductos(porcentaje,'Cargando productos: '+registrocargadoproductos+' de '+totalregistroproductos);if(totalregistroproductos>registrocargadoproductos&&controldebusquedadProductos){window.setTimeout(function(){if(controldebusquedadProductos)ajax(registrocargadoproductos)},0)}else{controldebusquedadProductos=false;solicitudProductosActiva=null;finalizarProcesoProductos(100,'Búsqueda finalizada: '+registrocargadoproductos+' productos')}}}catch(x){controldebusquedadProductos=false;solicitudProductosActiva=null;finalizarProcesoProductos(0,'No se pudo completar la búsqueda','error');ver_vetana_informativa('LO SENTIMOS HA OCURRIDO UN ERROR');GuardarArchivosLog('Error: '+x+' \r\n Consola: '+r)}}});solicitudProductosActiva=peticion}
window.cancelarCargaProducto=function(){var porcentaje=Number((document.getElementById('porcentajeProgressProducto')||{}).textContent&&document.getElementById('porcentajeProgressProducto').textContent.replace('%',''))||0;controldebusquedadProductos=false;if(solicitudProductosActiva&&solicitudProductosActiva.readyState!==4)solicitudProductosActiva.abort();solicitudProductosActiva=null;finalizarProcesoProductos(porcentaje,'Búsqueda cancelada por el usuario','cancelado')};
window.buscarabmproducto=function(){if(controlacceso('BUSCARLISTADOPRODUCTOS','accion')===false)return;if(controldebusquedadProductos){ver_vetana_informativa('CANCELE LA BUSQUEDA ACTUAL PARA CONTINUAR');return}controldebusquedadProductos=true;registros=[];var tablaProductos=document.getElementById('table_abm_producto');if(tablaProductos)tablaProductos.innerHTML=typeof paginacargando==='string'?paginacargando:'<div class="productos-estado-tabla">Preparando la búsqueda de productos...</div>';mostrarProcesoProductos(0,'Preparando la carga de productos');window.setTimeout(function(){if(controldebusquedadProductos)ajax()},0)};window.buscarabmmasproducto=function(){if(!controldebusquedadProductos)controldebusquedadProductos=true;mostrarProcesoProductos(totalregistroproductos>0?Math.round((registrocargadoproductos*100)/totalregistroproductos):0,'Continuando la carga de productos');window.setTimeout(function(){if(controldebusquedadProductos)ajax(registrocargadoproductos)},0)};
document.addEventListener('DOMContentLoaded',montar);document.addEventListener('keydown',function(x){if(x.key==='Escape'){cerrarFiltrosProductoListado();cerrarColumnasProductoListado()}});
}());
